// GENERATED BY BRUTE
// Riddlersoft.Core.Switch.NSwitch

#include <mscorlib/1nternal/Brute.h>

#include "Riddlersoft.Core/Riddlersoft/Core/Switch/NSwitch.h"
#include "mscorlib/System/String.h"
#include <mscorlib/1nternal/RuntimeType.h>
extern ::System::String* __String_A2F1031B_save__;

#include "mscorlib/System/String.inl"
#include <mscorlib/1nternal/RuntimeType.inl>

::System::String* Riddlersoft::Core::Switch::NSwitch::SavePath;
bool Riddlersoft::Core::Switch::NSwitch::Mounted = 0;

void BRUTE_InitConstStrings_NSwitch_5F5B0523()
{
   Riddlersoft::Core::Switch::NSwitch::SavePath = __String_A2F1031B_save__;
}

namespace Riddlersoft { namespace Core { namespace Switch { 

void NSwitch::$StaticCtor()
{
   ::Riddlersoft::Core::Switch::NSwitch::Mounted = false;
}

bool NSwitch$_$S_MountRom()
{
   BRUTE_GC_CHECK;
   bool var_0_09 = 0;
   bool var_1_1D = 0;
   var_0_09 = !::Riddlersoft::Core::Switch::NSwitch::Mounted;
   if ( !!var_0_09 )
   {
      ::Riddlersoft::Core::Switch::NSwitch::Mounted = NSwitch$_$S_Mount();
      var_1_1D = ::Riddlersoft::Core::Switch::NSwitch::Mounted;
   }
   else
   {
      var_1_1D = true;
   }
   return var_1_1D;
}

void NSwitch$_$S_UnmountRom()
{
   bool var_0_06 = 0;
   var_0_06 = ::Riddlersoft::Core::Switch::NSwitch::Mounted;
   if ( !!var_0_06 )
   {
      ::Riddlersoft::Core::Switch::NSwitch::Mounted = false;
      NSwitch$_$S_Unmount();
   }
}

}}} // namespace Riddlersoft.Core.Switch

